apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  type: ClusterIP
  selector:
    app: memcached
  ports:
    - name: http
      protocol: TCP
      port: 11211
      targetPort: 11211
