apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  serviceName: "not-applicable"
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 11211
          envFrom:
            - configMapRef:
                name: memcached-configmap
            - secretRef:
                name: memcached-secret
          volumeMounts:
            - mountPath: "/var/lib/memcached"
              name: memcached-volume
      volumes:
        - name: memcached-volume
          persistentVolumeClaim:
            claimName: memcached-pvc
