apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanout
  labels:
    app: fanout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fanout
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: fanout
    spec:
      containers:
        - name: fanout
          image: fanout
          ports:
            - containerPort: 5000
